/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cantor.h"

bool_t
xdr_pair (XDR *xdrs, pair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pairs (XDR *xdrs, pairs *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->pairs_val, (u_int *) &objp->pairs_len, ~0,
		sizeof (pair), (xdrproc_t) xdr_pair))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_results (XDR *xdrs, results *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->results_val, (u_int *) &objp->results_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
