/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cantor.h"
#include "math.h"
results *
cantorforeward_1_svc(pairs *pairs, struct svc_req *rqstp)
{
	static results  result;
    pair pairy; int i,x,y;
    result.results_len = pairs->pairs_len;
    result.results_val = (int *) malloc(sizeof(int) * pairs->pairs_len);
    printf("\n server is up and running");
    for(i=0; i <pairs->pairs_len; i++){
        x = pairs->pairs_val[i].x;
        y = pairs->pairs_val[i].y;
        result.results_val[i] = (( (x+y+1) * (x +y) ) /2 ) + y;
    } 

    

	return &result;
}

pairs *
cantorbackward_1_svc(results *results, struct svc_req *rqstp)
{
	static pairs  result;
    static int x,y,w,t,i,z;
    result.pairs_len = results->results_len;
    result.pairs_val = (pairs *) malloc(sizeof(pairs) * result.pairs_len );
    for(i=0; i < results->results_len; i++){
        z = results->results_val[i];
        w =  (sqrt(z+1) -1 ) /2;
        t = ((w*w) + w ) /2;
        y = z -t ;
        x = w -y;
        result.pairs_val[i].x =x;
        result.pairs_val[i].y =y;
    }
    
    
	return &result;
}
